// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/getAddressFromPostalCode.ts";
import * as $$$$$$$$$1 from "./actions/simulateShipping.ts";
import * as $$$0 from "./loaders/storeConfig.ts";
import * as $$$1 from "./loaders/verifiedReviews.ts";
import * as $$$2 from "./loaders/verifiedReviewsPDP.ts";

const manifest = {
  "loaders": {
    "deco-components/loaders/storeConfig.ts": $$$0,
    "deco-components/loaders/verifiedReviews.ts": $$$1,
    "deco-components/loaders/verifiedReviewsPDP.ts": $$$2,
  },
  "actions": {
    "deco-components/actions/getAddressFromPostalCode.ts": $$$$$$$$$0,
    "deco-components/actions/simulateShipping.ts": $$$$$$$$$1,
  },
  "name": "deco-components",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
